### ISSUE TITLE
[Kommentierung 1.5.3] A_23167 - Performance - Rohdaten - Spezifika KIM message-Block

### ISSUE THREAD

**Issue by CLAM01** [gematik/api-kim#46]
![image](https://github.com/gematik/api-kim/assets/115494634/130e46aa-7bb2-4fde-a71a-7fdf893bf263)

Wenn hier von $size gesprochen wird, welche Größe soll denn da rein wenn z.B. eine KAS Mail versendet worden ist.
ist $size dann die gesamte Größe inkl. KAS size oder nur die size, die im MAIL FROM nach der Verarbeitung gemäß Spec herauskommt?

**Comment by dhufnagel** [comment]
Die KAS Size sollte im X-KIM-KAS-Size zusätzlich vorhanden sein

**Comment by CLAM01** [comment]
stimmt... DONE
